default_stages: [commit]
repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black --check .
    language: system
    types: [python]
    pass_filenames: false
- repo: local
  hooks:
  - id: lint
    name: lint
    entry: poetry run flake8
    language: system
    types: [python]
    pass_filenames: false
# install using: pre-commit install --hook-type pre-push 
- repo: local
  hooks:
  - id: tests
    name: tests
    stages: [push]
    entry: poetry run pytest
    language: system
    types: [python]
    pass_filenames: false