default_stages: [commit]
repos:
- repo: local
  hooks:
  - id: lint
    name: lint
    entry: poetry run black --check .
    language: system
    types: [python]
    pass_filenames: false
- repo: local
  hooks:
  - id: tests
    name: tests
    entry: poetry run pytest
    language: system
    types: [python]
    pass_filenames: false