[tool.poetry]
name = "finyl"
version = "0.1.0"
description = ""
authors = ["dakaugu <dakaugu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0" 
pydub = "^0.25.1"
simpleaudio = "^1.0.4"
pytube = "^15.0.0"

[tool.poetry.dev-dependencies]
ipython = "^8.17.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
